del WebApplication.sln

dotnet new sln -n WebApplication

dotnet sln WebApplication.sln add ..\Bookshelf\Nameless.Bookshelf.Core\Nameless.Bookshelf.Core.csproj
dotnet sln WebApplication.sln add .\Nameless.WebApplication.Core\Nameless.WebApplication.Core.csproj
dotnet sln WebApplication.sln add .\Nameless.WebApplication.Web\Nameless.WebApplication.Web.csproj
dotnet sln WebApplication.sln add ..\..\src\Nameless.Caching\Nameless.Caching.csproj
dotnet sln WebApplication.sln add ..\..\src\Nameless.Core\Nameless.Core.csproj
dotnet sln WebApplication.sln add ..\..\src\Nameless.CQRS\Nameless.CQRS.csproj
dotnet sln WebApplication.sln add ..\..\src\Nameless.Environment\Nameless.Environment.csproj
dotnet sln WebApplication.sln add ..\..\src\Nameless.FileStorage\Nameless.FileStorage.csproj
dotnet sln WebApplication.sln add ..\..\src\Nameless.IO\Nameless.IO.csproj
dotnet sln WebApplication.sln add ..\..\src\Nameless.IoC\Nameless.IoC.csproj
dotnet sln WebApplication.sln add ..\..\src\Nameless.Localization\Nameless.Localization.csproj
dotnet sln WebApplication.sln add ..\..\src\Nameless.Logging\Nameless.Logging.csproj
dotnet sln WebApplication.sln add ..\..\src\Nameless.Mailing\Nameless.Mailing.csproj
dotnet sln WebApplication.sln add ..\..\src\Nameless.Notification\Nameless.Notification.csproj
dotnet sln WebApplication.sln add ..\..\src\Nameless.ObjectMapper\Nameless.ObjectMapper.csproj
dotnet sln WebApplication.sln add ..\..\src\Nameless.Patterns\Nameless.Patterns.csproj
dotnet sln WebApplication.sln add ..\..\src\Nameless.Persistence\Nameless.Persistence.csproj
dotnet sln WebApplication.sln add ..\..\src\Nameless.PubSub\Nameless.PubSub.csproj
dotnet sln WebApplication.sln add ..\..\src\Nameless.Search\Nameless.Search.csproj
dotnet sln WebApplication.sln add ..\..\src\Nameless.Security\Nameless.Security.csproj
dotnet sln WebApplication.sln add ..\..\src\Nameless.Serialization\Nameless.Serialization.csproj
dotnet sln WebApplication.sln add ..\..\src\Nameless.Services\Nameless.Services.csproj
dotnet sln WebApplication.sln add ..\..\src\Nameless.Text\Nameless.Text.csproj
dotnet sln WebApplication.sln add ..\..\impl\Nameless.AspNetCore\Nameless.AspNetCore.csproj
dotnet sln WebApplication.sln add ..\..\impl\Nameless.Caching.InMemory\Nameless.Caching.InMemory.csproj
dotnet sln WebApplication.sln add ..\..\impl\Nameless.CQRS.Common\Nameless.CQRS.Common.csproj
dotnet sln WebApplication.sln add ..\..\impl\Nameless.Environment.Common\Nameless.Environment.Common.csproj
dotnet sln WebApplication.sln add ..\..\impl\Nameless.FileProvider.Common\Nameless.FileProvider.Common.csproj
dotnet sln WebApplication.sln add ..\..\impl\Nameless.FileStorage.FileSystem\Nameless.FileStorage.FileSystem.csproj
dotnet sln WebApplication.sln add ..\..\impl\Nameless.IoC.Autofac\Nameless.IoC.Autofac.csproj
dotnet sln WebApplication.sln add ..\..\impl\Nameless.Localization.Json\Nameless.Localization.Json.csproj
dotnet sln WebApplication.sln add ..\..\impl\Nameless.Logging.Log4net\Nameless.Logging.Log4net.csproj
dotnet sln WebApplication.sln add ..\..\impl\Nameless.Mailing.MailKit\Nameless.Mailing.MailKit.csproj
dotnet sln WebApplication.sln add ..\..\impl\Nameless.NHibernate\Nameless.NHibernate.csproj
dotnet sln WebApplication.sln add ..\..\impl\Nameless.Notification.Common\Nameless.Notification.Common.csproj
dotnet sln WebApplication.sln add ..\..\impl\Nameless.ObjectMapper.AutoMapper\Nameless.ObjectMapper.AutoMapper.csproj
dotnet sln WebApplication.sln add ..\..\impl\Nameless.Persistence.NHibernate\Nameless.Persistence.NHibernate.csproj
dotnet sln WebApplication.sln add ..\..\impl\Nameless.PubSub.Common\Nameless.PubSub.Common.csproj
dotnet sln WebApplication.sln add ..\..\impl\Nameless.Search.Lucene\Nameless.Search.Lucene.csproj
dotnet sln WebApplication.sln add ..\..\impl\Nameless.Security.Common\Nameless.Security.Common.csproj
dotnet sln WebApplication.sln add ..\..\impl\Nameless.Serialization.Json\Nameless.Serialization.Json.csproj
dotnet sln WebApplication.sln add ..\..\impl\Nameless.Services.Common\Nameless.Services.Common.csproj
dotnet sln WebApplication.sln add ..\..\impl\Nameless.Text.Common\Nameless.Text.Common.csproj
dotnet sln WebApplication.sln add ..\..\extra\Nameless.Caching.InMemory.Extra\Nameless.Caching.InMemory.Extra.csproj
dotnet sln WebApplication.sln add ..\..\extra\Nameless.CQRS.Common.Extra\Nameless.CQRS.Common.Extra.csproj
dotnet sln WebApplication.sln add ..\..\extra\Nameless.Environment.Common.Extra\Nameless.Environment.Common.Extra.csproj
dotnet sln WebApplication.sln add ..\..\extra\Nameless.FileProvider.Physical.Extra\Nameless.FileProvider.Physical.Extra.csproj
dotnet sln WebApplication.sln add ..\..\extra\Nameless.FileStorage.FileSystem.Extra\Nameless.FileStorage.FileSystem.Extra.csproj
dotnet sln WebApplication.sln add ..\..\extra\Nameless.IoC.Autofac.Extra\Nameless.IoC.Autofac.Extra.csproj
dotnet sln WebApplication.sln add ..\..\extra\Nameless.Localization.Json.Extra\Nameless.Localization.Json.Extra.csproj
dotnet sln WebApplication.sln add ..\..\extra\Nameless.Logging.Log4net.Extra\Nameless.Logging.Log4net.Extra.csproj
dotnet sln WebApplication.sln add ..\..\extra\Nameless.Mailing.Mailkit.Extra\Nameless.Mailing.Mailkit.Extra.csproj
dotnet sln WebApplication.sln add ..\..\extra\Nameless.NHibernate.Extra\Nameless.NHibernate.Extra.csproj
dotnet sln WebApplication.sln add ..\..\extra\Nameless.Notification.Common.Extra\Nameless.Notification.Common.Extra.csproj
dotnet sln WebApplication.sln add ..\..\extra\Nameless.ObjectMapper.AutoMapper.Extra\Nameless.ObjectMapper.AutoMapper.Extra.csproj
dotnet sln WebApplication.sln add ..\..\extra\Nameless.Persistence.NHibernate.Extra\Nameless.Persistence.NHibernate.Extra.csproj
dotnet sln WebApplication.sln add ..\..\extra\Nameless.PubSub.Common.Extra\Nameless.PubSub.Common.Extra.csproj
dotnet sln WebApplication.sln add ..\..\extra\Nameless.Search.Lucene.Extra\Nameless.Search.Lucene.Extra.csproj
dotnet sln WebApplication.sln add ..\..\extra\Nameless.Security.Common.Extra\Nameless.Security.Common.Extra.csproj
dotnet sln WebApplication.sln add ..\..\extra\Nameless.Serialization.Json.Extra\Nameless.Serialization.Json.Extra.csproj
dotnet sln WebApplication.sln add ..\..\extra\Nameless.Services.Common.Extra\Nameless.Services.Common.Extra.csproj
dotnet sln WebApplication.sln add ..\..\extra\Nameless.Text.Common.Extra\Nameless.Text.Common.Extra.csproj