//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nameless.WPF.Client.Sqlite.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nameless.WPF.Client.Sqlite.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base de Dados SQLite....
        /// </summary>
        internal static string InitializeSqliteDatabaseStep_DisplayName {
            get {
                return ResourceManager.GetString("InitializeSqliteDatabaseStep_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplicando migrações na base de dados....
        /// </summary>
        internal static string InitializeSqliteDatabaseStep_Progress_ApplyingMigrations {
            get {
                return ResourceManager.GetString("InitializeSqliteDatabaseStep_Progress_ApplyingMigrations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicialização concluída com sucesso..
        /// </summary>
        internal static string InitializeSqliteDatabaseStep_Progress_Complete {
            get {
                return ResourceManager.GetString("InitializeSqliteDatabaseStep_Progress_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assegurando existência da base de dados....
        /// </summary>
        internal static string InitializeSqliteDatabaseStep_Progress_EnsureDatabaseExistence {
            get {
                return ResourceManager.GetString("InitializeSqliteDatabaseStep_Progress_EnsureDatabaseExistence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarefa de inicialização ignorada, pois a base de dados não é relacional..
        /// </summary>
        internal static string InitializeSqliteDatabaseStep_Progress_NonRelationalDatabase {
            get {
                return ResourceManager.GetString("InitializeSqliteDatabaseStep_Progress_NonRelationalDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicializando base de dados....
        /// </summary>
        internal static string InitializeSqliteDatabaseStep_Progress_Start {
            get {
                return ResourceManager.GetString("InitializeSqliteDatabaseStep_Progress_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup da Base de Dados SQLite.
        /// </summary>
        internal static string SqliteDisasterRecoveryRoutine_Name {
            get {
                return ResourceManager.GetString("SqliteDisasterRecoveryRoutine_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro durante a execução do backup da base de dados SQLite. Erro: {0}.
        /// </summary>
        internal static string SqliteDisasterRecoveryRoutine_Report_Backup_Failure {
            get {
                return ResourceManager.GetString("SqliteDisasterRecoveryRoutine_Report_Backup_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciando o backup dos dados da base SQLite....
        /// </summary>
        internal static string SqliteDisasterRecoveryRoutine_Report_Backup_Starting {
            get {
                return ResourceManager.GetString("SqliteDisasterRecoveryRoutine_Report_Backup_Starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup da base de dados SQLite concluído com sucesso..
        /// </summary>
        internal static string SqliteDisasterRecoveryRoutine_Report_Backup_Success {
            get {
                return ResourceManager.GetString("SqliteDisasterRecoveryRoutine_Report_Backup_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível localizar o arquivo da base de dados SQLite da aplicação. Certifique-se que a aplicação foi inicializada corretamente e que a base de dados esteja no diretório corrrespondente..
        /// </summary>
        internal static string SqliteDisasterRecoveryRoutine_Report_Missing_Application_Database_File {
            get {
                return ResourceManager.GetString("SqliteDisasterRecoveryRoutine_Report_Missing_Application_Database_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível localizar o arquivo de backup da base de dados SQLite. Certifique-se que ele se encontra no diretório temporário ou que existe um arquivo de backup válido..
        /// </summary>
        internal static string SqliteDisasterRecoveryRoutine_Report_Missing_Backup_Database_File {
            get {
                return ResourceManager.GetString("SqliteDisasterRecoveryRoutine_Report_Missing_Backup_Database_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciando a restauração dos dados da base SQLite....
        /// </summary>
        internal static string SqliteDisasterRecoveryRoutine_Report_Restore_Starting {
            get {
                return ResourceManager.GetString("SqliteDisasterRecoveryRoutine_Report_Restore_Starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restauração da base de dados SQLite concluído com sucesso..
        /// </summary>
        internal static string SqliteDisasterRecoveryRoutine_Report_Restore_Success {
            get {
                return ResourceManager.GetString("SqliteDisasterRecoveryRoutine_Report_Restore_Success", resourceCulture);
            }
        }
    }
}
