using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Nameless.Web.Http.Endpoints.Generator.Models;
using Nameless.Web.Http.Endpoints.Generator.Pipeline.Metadata;

namespace Nameless.Web.Http.Endpoints.Generator.Emitters;

internal static class EndpointEmitter {
    internal static (string HintName, string Source) Emit(EndpointModel model) {
        var sb = new StringBuilder();

        EmitFileHeader(sb);
        EmitPartialClass(sb, model);

        var code = sb.ToString();
        var tree = CSharpSyntaxTree.ParseText(code);
        var root = tree.GetRoot().NormalizeWhitespace();

        var hintName = string.IsNullOrEmpty(model.Namespace)
            ? $"{model.ClassName}.g.cs"
            : $"{model.Namespace}.{model.ClassName}.g.cs";

        return (hintName, root.ToFullString());
    }

    private static void EmitFileHeader(StringBuilder sb) {
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine($"// Generated by {PROJECT_NAME} — do not edit.");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using global::Microsoft.AspNetCore.Builder;");
        sb.AppendLine("using global::Microsoft.AspNetCore.Routing;");
        sb.AppendLine("using global::Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using global::Microsoft.Extensions.DependencyInjection.Extensions;");
        sb.AppendLine();
    }

    private static void EmitPartialClass(StringBuilder sb, EndpointModel endpoint) {
        if (!string.IsNullOrEmpty(endpoint.Namespace)) {
            sb.AppendLine($"namespace {endpoint.Namespace};");
            sb.AppendLine();
        }

        sb.AppendLine($"{endpoint.ClassAccessModifier} partial class {endpoint.ClassName}");
        sb.AppendLine("{");
        EmitRegister(sb, endpoint);
        EmitMap(sb, endpoint);
        sb.AppendLine("}");
    }

    private static void EmitRegister(StringBuilder sb, EndpointModel endpoint) {
        sb.AppendLine($"{endpoint.ClassAccessModifier} static void Register({NewFQN.ServiceCollection} services)");
        sb.AppendLine("{");
        sb.AppendLine($"services.TryAddTransient<global::{endpoint.FullClassName}>();");
        sb.AppendLine("}");
    }

    private static void EmitMap(StringBuilder sb, EndpointModel model) {
        sb.AppendLine($"internal static void Map({NewFQN.EndpointRouteBuilder} {BUILDER_REF})");
        sb.AppendLine("{");

        var endpointVar = $"_ep_{model.ClassName}";
        var routeTemplate = EscapeStringLiteral(model.Route);

        sb.AppendLine(
            $"{BUILDER_REF}.Map{model.HttpVerb}(\"{routeTemplate}\", static async ("
        );

        var parameters = model.HandlerParameters.Select(BuildParameterDeclaration).ToList();
        parameters.Add($"[{NewFQN.FromServices}] global::{model.FullClassName} {endpointVar}");
        sb.AppendLine(string.Join(", ", parameters));

        sb.AppendLine(") =>");

        var callArgs = string.Join(", ", model.HandlerParameters.Select(static parameter => parameter.Name));
        sb.Append($"await {endpointVar}.{model.Handler?.Name}({callArgs}).ConfigureAwait(false))");

        foreach (var convention in model.Conventions) {
            sb.AppendLine($".{convention.Call}");
        }

        sb.AppendLine(";");
        sb.AppendLine("}");
    }
    
    private static string BuildParameterDeclaration(HandlerParameterMetadata param) {
        var bindingName = EscapeStringLiteral(param.BindingName);
        var attrPrefix = param.BindingKind switch {
            ParameterBindingKind.AsParameters => $"[{NewFQN.AsParameters}] ",

            ParameterBindingKind.FromBody => $"[{NewFQN.FromBody}] ",

            ParameterBindingKind.FromForm => $"[{NewFQN.FromForm}] ",

            ParameterBindingKind.FromHeader => string.IsNullOrWhiteSpace(bindingName)
                    ? $"[{NewFQN.FromHeader}] "
                    : $"[{NewFQN.FromHeader}(Name = \"{bindingName}\")] ",

            ParameterBindingKind.FromQuery => string.IsNullOrWhiteSpace(bindingName)
                    ? $"[{NewFQN.FromQuery}] "
                    : $"[{NewFQN.FromQuery}(Name = \"{bindingName}\")] ",

            ParameterBindingKind.FromRoute => string.IsNullOrWhiteSpace(bindingName)
                    ? $"[{NewFQN.FromRoute}] "
                    : $"[{NewFQN.FromRoute}(Name = \"{bindingName}\")] ",

            _ => string.Empty
        };

        return $"{attrPrefix}{param.FullTypeName} {param.Name}";
    }
}
