using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Nameless.Web.Http.Endpoints.Generator.Models;

namespace Nameless.Web.Http.Endpoints.Generator.Emitters;

internal static class EndpointEmitter {
    internal static (string HintName, string Source) Emit(EndpointModel endpoint) {
        var sb = new StringBuilder();

        EmitFileHeader(sb);
        EmitPartialClass(sb, endpoint);

        var code = sb.ToString();
        var tree = CSharpSyntaxTree.ParseText(code);
        var root = tree.GetRoot().NormalizeWhitespace();

        var hintName = string.IsNullOrEmpty(endpoint.Namespace)
            ? $"{endpoint.ClassName}.g.cs"
            : $"{endpoint.Namespace}.{endpoint.ClassName}.g.cs";

        return (hintName, root.ToFullString());
    }

    private static void EmitFileHeader(StringBuilder sb) {
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine($"// Generated by {PROJECT_NAME} — do not edit.");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using global::Microsoft.AspNetCore.Builder;");
        sb.AppendLine("using global::Microsoft.AspNetCore.Routing;");
        sb.AppendLine("using global::Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using global::Microsoft.Extensions.DependencyInjection.Extensions;");
        sb.AppendLine();
    }

    private static void EmitPartialClass(StringBuilder sb, EndpointModel endpoint) {
        if (!string.IsNullOrEmpty(endpoint.Namespace)) {
            sb.AppendLine($"namespace {endpoint.Namespace};");
            sb.AppendLine();
        }

        sb.AppendLine($"{endpoint.AccessModifier} partial class {endpoint.ClassName}");
        sb.AppendLine("{");
        EmitRegister(sb, endpoint);
        EmitMap(sb, endpoint);
        sb.AppendLine("}");
    }

    private static void EmitRegister(StringBuilder sb, EndpointModel endpoint) {
        sb.AppendLine($"internal static void Register({FQN.SERVICE_COLLECTION} services)");
        sb.AppendLine("{");
        sb.AppendLine($"services.TryAddTransient<global::{endpoint.FullClassName}>();");
        sb.AppendLine("}");
    }

    private static void EmitMap(StringBuilder sb, EndpointModel endpoint) {
        sb.AppendLine($"internal static void Map({FQN.ENDPOINT_ROUTE_BUILDER} {BUILDER_REF})");
        sb.AppendLine("{");

        var endpointVar = $"_ep_{endpoint.ClassName}";
        var routeTemplate = EscapeStringLiteral(endpoint.Metadata.RouteTemplate);

        sb.AppendLine(
            $"{BUILDER_REF}.Map{endpoint.Metadata.HttpMethod}(\"{routeTemplate}\", static async ("
        );

        var parameters = endpoint.Parameters
                                 .Select(BuildParameterDeclaration)
                                 .ToList();
        parameters.Add($"[{FQN.FROM_SERVICES}] global::{endpoint.FullClassName} {endpointVar}");
        sb.AppendLine(string.Join(", ", parameters));

        sb.AppendLine(") =>");

        var callArgs = string.Join(", ", endpoint.Parameters.Select(static p => p.Name));
        sb.Append($"await {endpointVar}.HandleAsync({callArgs}).ConfigureAwait(false))");

        foreach (var version in endpoint.Versions) {
            sb.Append($".MapToApiVersion(new {FQN.API_VERSION}({version.Major}, {version.Minor}))");
        }

        foreach (var produces in endpoint.Produces) {
            EmitProduces(sb, produces);
        }

        if (endpoint.AcceptsTypeName is not null) {
            sb.Append($".Accepts<{endpoint.AcceptsTypeName}>(");
            if (endpoint.AcceptsContentType is not null) {
                sb.Append($"\"{EscapeStringLiteral(endpoint.AcceptsContentType)}\"");
            }
            sb.Append(')');
        }

        foreach (var filter in endpoint.FilterTypeNames) {
            sb.Append($".AddEndpointFilter<{filter}>()");
        }

        if (endpoint.RequiresAuthorization) {
            sb.Append(".RequireAuthorization(");
            if (endpoint.AuthorizationPolicy is not null) {
                sb.Append($"\"{EscapeStringLiteral(endpoint.AuthorizationPolicy)}\"");
            }
            sb.Append(')');
        }

        if (endpoint.AllowAnonymous) {
            sb.Append(".AllowAnonymous()");
        }

        if (endpoint.CorsPolicy is not null) {
            sb.Append($".RequireCors(\"{EscapeStringLiteral(endpoint.CorsPolicy)}\")");
        }

        if (endpoint.RateLimitingPolicy is not null) {
            sb.Append($".RequireRateLimiting(\"{EscapeStringLiteral(endpoint.RateLimitingPolicy)}\")");
        }

        if (endpoint.OutputCachePolicy is not null) {
            sb.Append($".CacheOutput(\"{EscapeStringLiteral(endpoint.OutputCachePolicy)}\")");
        }

        if (endpoint.RequestTimeoutPolicy is not null) {
            sb.Append($".WithRequestTimeout(\"{EscapeStringLiteral(endpoint.RequestTimeoutPolicy)}\")");
        }

        if (endpoint.DisableHttpMetrics) {
            sb.Append(".DisableHttpMetrics()");
        }

        if (endpoint.RequireAntiforgery == true) {
            sb.Append(".RequireAntiforgery()");
        }
        else if (endpoint.RequireAntiforgery == false) {
            sb.Append(".DisableAntiforgery()");
        }

        if (endpoint.Summary is not null) {
            sb.Append($".WithSummary(\"{EscapeStringLiteral(endpoint.Summary)}\")");
        }

        if (endpoint.Description is not null) {
            sb.Append($".WithDescription(\"{EscapeStringLiteral(endpoint.Description)}\")");
        }

        var endpointDisplayName = endpoint.Metadata.EndpointName ?? endpoint.ClassName;
        sb.Append($".WithName(\"{EscapeStringLiteral(endpointDisplayName)}\")");

        if (!endpoint.Metadata.Tags.IsEmpty) {
            var tagLiterals = string.Join(
                separator: ", ",
                values: endpoint.Metadata.Tags.Select(static tag => $"\"{EscapeStringLiteral(tag)}\"")
            );
            sb.Append($".WithTags({tagLiterals})");
        }

        sb.AppendLine(";");
        sb.AppendLine("}");
    }

    private static void EmitProduces(StringBuilder sb, ProducesModel produces) {
        switch (produces.Kind) {
            case ProducesKind.Response:
                var ct = produces.ContentType ?? "application/json";
                sb.Append($".Produces<{produces.FullTypeName}>(statusCode: {produces.StatusCode}, contentType: \"{ct}\")");
                break;
            case ProducesKind.Problem:
                var pct = produces.ContentType ?? "application/problem+json";
                sb.Append($".ProducesProblem(statusCode: {produces.StatusCode}, contentType: \"{pct}\")");
                break;
            case ProducesKind.ValidationProblem:
                var vpct = produces.ContentType ?? "application/problem+json";
                sb.Append($".ProducesValidationProblem(statusCode: {produces.StatusCode}, contentType: \"{vpct}\")");
                break;
        }
    }

    private static string BuildParameterDeclaration(ParameterModel param) {
        var bindingName = EscapeStringLiteral(param.BindingName);
        var attrPrefix = param.BindingKind switch {
            ParameterBindingKind.FromBody => $"[{FQN.FROM_BODY}] ",

            ParameterBindingKind.FromRoute => string.IsNullOrWhiteSpace(bindingName)
                    ? $"[{FQN.FROM_ROUTE}] "
                    : $"[{FQN.FROM_ROUTE}(Name = \"{bindingName}\")] ",

            ParameterBindingKind.FromQuery => string.IsNullOrWhiteSpace(bindingName)
                    ? $"[{FQN.FROM_QUERY}] "
                    : $"[{FQN.FROM_QUERY}(Name = \"{bindingName}\")] ",

            ParameterBindingKind.FromHeader => string.IsNullOrWhiteSpace(bindingName)
                    ? $"[{FQN.FROM_HEADER}] "
                    : $"[{FQN.FROM_HEADER}(Name = \"{bindingName}\")] ",

            ParameterBindingKind.AsParameters => $"[{FQN.AS_PARAMETERS}] ",

            _ => string.Empty
        };

        return $"{attrPrefix}{param.FullTypeName} {param.Name}";
    }
}
