using Nameless.Web.Http.Endpoints.Generator.Infrastructure;
using Nameless.Web.Http.Endpoints.Generator.Models;

namespace Nameless.Web.Http.Endpoints.Generator.Emitters;

public static class EndpointEmitter {
    public static (string HintName, string Source) Emit(EndpointModel endpoint) {
        var cw = new CodeWriter();

        EmitFileHeader(cw, endpoint);
        EmitClass(cw, endpoint);

        var hintName = $"{Sanitize(endpoint.Class.FullName)}.g.cs";
        var code = cw.GetCode();

        return (hintName, code);
    }

    private static void EmitFileHeader(CodeWriter cw, EndpointModel endpoint) {
        cw.WriteLine("// <auto-generated/>");
        cw.WriteLine($"// Generated by {Project.Name} — do not edit.");
        cw.WriteLine("#nullable enable");
        cw.WriteLine();
        cw.WriteLine("using Microsoft.Extensions.DependencyInjection.Extensions;");
        cw.WriteLine();

        if (string.IsNullOrEmpty(endpoint.Class.Namespace)) {
            return;
        }

        cw.WriteLine($"namespace {endpoint.Class.Namespace};");
        cw.WriteLine();
    }

    private static void EmitClass(CodeWriter cw, EndpointModel endpoint) {
        using (cw.Block($"{endpoint.Class.AccessorModifier} partial class {endpoint.Class.Name} {{")) {
            cw.WriteLine();
            EmitRegister(cw, endpoint);

            cw.WriteLine();
            EmitMap(cw, endpoint);
        }
    }

    private static void EmitRegister(CodeWriter cw, EndpointModel endpoint) {
        using (cw.Block($"{endpoint.Class.AccessorModifier} static void Register({FQN.Microsoft.ServiceCollection} services) {{")) {
            cw.WriteLine($"services.TryAddTransient<global::{endpoint.Class.FullName}>();");
        }
    }

    private static void EmitMap(CodeWriter cw, EndpointModel endpoint) {
        const string BuilderArgName = "builder";
        const string EndpointVarName = "_ep_";

        var routeTemplate = EscapeStringLiteral(endpoint.Arguments.Route);

        using (cw.Block($"{endpoint.Class.AccessorModifier} static void Map({FQN.Microsoft.EndpointRouteBuilder} {BuilderArgName}) {{")) {
            cw.WriteLine($"{BuilderArgName}.Map{endpoint.Arguments.HttpVerb}(\"{routeTemplate}\", static async (");
            cw.Indent().Indent();

            var parameters = endpoint.Handler.Parameters.Select(BuildParameterDeclaration).ToList();
            foreach (var parameter in parameters) {
                cw.WriteLine($"{parameter}, ");
            }

            cw.WriteLine($"[{FQN.Microsoft.FromServices}] global::{endpoint.Class.FullName} {EndpointVarName}");
            cw.Dedent();

            var callArgs = string.Join(", ", endpoint.Handler.Parameters.Select(static parameter => parameter.Name));
            cw.WriteLine($") => await {EndpointVarName}.{endpoint.Handler.Method.Name}({callArgs}).ConfigureAwait(false)");
            cw.Dedent();

            cw.Write(")");

            if (endpoint.Conventions.Count > 0) {
                cw.WriteLine();

                var allButLast = endpoint.Conventions.Take(endpoint.Conventions.Count - 1);
                foreach (var convention in allButLast) {
                    cw.WriteLine(convention);
                }

                var last = endpoint.Conventions.LastOrDefault();
                cw.WriteLine(last, closing: ";");
            } else { cw.Write(";"); }
        }
    }

    private static string BuildParameterDeclaration(EndpointHandlerParameterModel model) {
        var bindingName = EscapeStringLiteral(model.BindingName);
        var attrPrefix = model.BindingKind switch {
            ParameterBindingKind.AsParameters => $"[{FQN.Microsoft.AsParameters}] ",

            ParameterBindingKind.FromBody => $"[{FQN.Microsoft.FromBody}] ",

            ParameterBindingKind.FromForm => $"[{FQN.Microsoft.FromForm}] ",

            ParameterBindingKind.FromHeader => string.IsNullOrWhiteSpace(bindingName)
                    ? $"[{FQN.Microsoft.FromHeader}] "
                    : $"[{FQN.Microsoft.FromHeader}(Name = \"{bindingName}\")] ",

            ParameterBindingKind.FromQuery => string.IsNullOrWhiteSpace(bindingName)
                    ? $"[{FQN.Microsoft.FromQuery}] "
                    : $"[{FQN.Microsoft.FromQuery}(Name = \"{bindingName}\")] ",

            ParameterBindingKind.FromRoute => string.IsNullOrWhiteSpace(bindingName)
                    ? $"[{FQN.Microsoft.FromRoute}] "
                    : $"[{FQN.Microsoft.FromRoute}(Name = \"{bindingName}\")] ",

            _ => string.Empty
        };

        return $"{attrPrefix}{model.Type} {model.Name}";
    }
}
