using Nameless.Web.Http.Endpoints.Generator.Conventions;
using Nameless.Web.Http.Endpoints.Generator.Infrastructure;
using Nameless.Web.Http.Endpoints.Generator.Models;

namespace Nameless.Web.Http.Endpoints.Generator.Emitters;

public static class EndpointGroupEmitter {
    public static (string HintName, string Source) Emit(GroupingModel grouping) {
        var cw = new CodeWriter();

        EmitFileHeader(cw);
        EmitClass(cw, grouping);
        
        var hintName = $"{Sanitize(grouping.Class.FullName)}.g.cs";
        var code = cw.GetCode();

        return (hintName, code);
    }

    private static void EmitFileHeader(CodeWriter cw) {
        cw.WriteLine("// <auto-generated/>");
        cw.WriteLine($"// Generated by {Project.Name} — do not edit.");
        cw.WriteLine("#nullable enable");
    }

    private static void EmitClass(CodeWriter cw, GroupingModel grouping) {
        if (!string.IsNullOrEmpty(grouping.Class.Namespace)) {
            cw.WriteLine($"namespace {grouping.Class.Namespace};");
            cw.WriteLine();
        }

        using (cw.Block($"{grouping.Class.AccessorModifier} partial class {grouping.Class.Name} {{")) {
            EmitCreate(cw, grouping);
        }
    }

    private static void EmitCreate(CodeWriter cw, GroupingModel grouping) {
        const string BuilderArgName = "builder";
        const string GroupVarName = "result";
        const string VersionSetVarName = "vs";
        
        using (cw.Block($"{grouping.Class.AccessorModifier} static {FQN.Microsoft.EndpointRouteBuilder} Create({FQN.Microsoft.EndpointRouteBuilder} {BuilderArgName}) {{")) {
            if (grouping.ReportVersions.Length > 0) {
                using (cw.Block($"var {VersionSetVarName} = {BuilderArgName}.NewApiVersionSet()", closing: string.Empty)) {
                    foreach (var version in grouping.ReportVersions) {
                        var major = $"majorVersion: {version.Major}";
                        var minor = $"minorVersion: {(version.Minor is not null ? version.Minor.ToString() : "null")}";
                        var status = $"status: {(!string.IsNullOrWhiteSpace(version.Status) ? $"\"{EscapeStringLiteral(version.Status)}\"" : "null")}";

                        cw.WriteLine($".HasApiVersion(new {FQN.AspVersioning.ApiVersion}({major}, {minor}, {status}))");
                    }

                    cw.WriteLine(".ReportApiVersions()");
                    cw.WriteLine(".Build();");
                }

                grouping.Conventions.Add(new Convention(
                    call: $".WithApiVersionSet({VersionSetVarName})"
                ));
            }

            using (cw.Block($"var {GroupVarName} = {BuilderArgName}.MapGroup(\"{EscapeStringLiteral(grouping.Arguments.Prefix)}\")", closing: string.Empty)) {
                if (grouping.Conventions.Count > 0) {
                    var allButLast = grouping.Conventions.Take(grouping.Conventions.Count - 1);
                    foreach (var convention in allButLast) {
                        cw.WriteLine(convention);
                    }

                    var last = grouping.Conventions.LastOrDefault();
                    cw.WriteLine(last, closing: ";");
                }
                else { cw.Write(";"); }
            }
            
            cw.WriteLine($"return {GroupVarName};");
        }
    }
}
