using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Nameless.Web.Http.Endpoints.Generator.Models;
using Nameless.Web.Http.Endpoints.Generator.Pipeline;

namespace Nameless.Web.Http.Endpoints.Generator.Emitters;

internal static class GroupEmitter {
    internal static GroupingMetadata Emit(GroupModel group) {
        var sb = new StringBuilder();

        EmitFileHeader(sb);
        EmitPartialClass(sb, group);

        var code = sb.ToString();
        var tree = CSharpSyntaxTree.ParseText(code);
        var root = tree.GetRoot().NormalizeWhitespace();

        var hintName = string.IsNullOrEmpty(group.Namespace)
            ? $"{group.ClassName}.g.cs"
            : $"{group.Namespace}.{group.ClassName}.g.cs";

        return new GroupingMetadata(hintName, root.ToFullString());
    }

    private static void EmitFileHeader(StringBuilder sb) {
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine($"// Generated by {PROJECT_NAME} — do not edit.");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using global::Asp.Versioning;");
        sb.AppendLine("using global::Microsoft.AspNetCore.Builder;");
        sb.AppendLine("using global::Microsoft.AspNetCore.Routing;");
        sb.AppendLine();
    }

    private static void EmitPartialClass(StringBuilder sb, GroupModel group) {
        if (!string.IsNullOrEmpty(group.Namespace)) {
            sb.AppendLine($"namespace {group.Namespace};");
            sb.AppendLine();
        }

        sb.AppendLine($"{group.AccessModifier} partial class {group.ClassName}");
        sb.AppendLine("{");
        EmitCreate(sb, group);
        sb.AppendLine("}");
    }

    private static void EmitCreate(StringBuilder sb, GroupModel group) {
        sb.AppendLine($"{group.AccessModifier} static {FQN.ROUTE_GROUP_BUILDER} Create({FQN.ENDPOINT_ROUTE_BUILDER} {BUILDER_REF})");
        sb.AppendLine("{");

        var groupVar = $"_group_{Sanitize(group.Name)}";

        if (!group.Versions.IsEmpty) {
            var versionSetVar = $"_version_set_{Sanitize(group.Name)}";
            sb.AppendLine($"var {versionSetVar} = {BUILDER_REF}.NewApiVersionSet()");

            foreach (var version in group.Versions) {
                var method = version.Deprecated ? "HasDeprecatedApiVersion" : "HasApiVersion";
                sb.AppendLine($".{method}(new {FQN.API_VERSION}({version.Major}, {version.Minor}))");
            }

            sb.AppendLine(".ReportApiVersions().Build();");
            sb.AppendLine($"var {groupVar} = {BUILDER_REF}.MapGroup(\"{EscapeStringLiteral(group.Prefix)}\");");
            sb.AppendLine($"{groupVar}.WithApiVersionSet({versionSetVar});");
        }
        else {
            sb.AppendLine($"var {groupVar} = {BUILDER_REF}.MapGroup(\"{EscapeStringLiteral(group.Prefix)}\");");
        }

        EmitGroupMetadata(sb, group, groupVar);

        sb.AppendLine($"return {groupVar};");
        sb.AppendLine("}");
    }

    private static void EmitGroupMetadata(StringBuilder sb, GroupModel group, string groupVar) {
        if (group.RateLimitingPolicy is not null) {
            sb.AppendLine($"{groupVar}.RequireRateLimiting(\"{EscapeStringLiteral(group.RateLimitingPolicy)}\");");
        }

        if (group.DisableRateLimiting) {
            sb.AppendLine($"{groupVar}.DisableRateLimiting();");
        }

        if (group.DisableAntiforgery) {
            sb.AppendLine($"{groupVar}.DisableAntiforgery();");
        }

        if (group.DisableHttpMetrics) {
            sb.AppendLine($"{groupVar}.DisableHttpMetrics();");
        }

        if (group.OutputCachePolicy is not null) {
            sb.AppendLine($"{groupVar}.CacheOutput(\"{EscapeStringLiteral(group.OutputCachePolicy)}\");");
        }

        if (group.CorsPolicy is not null) {
            sb.AppendLine($"{groupVar}.RequireCors(\"{EscapeStringLiteral(group.CorsPolicy)}\");");
        }

        if (group.AllowAnonymous) {
            sb.AppendLine($"{groupVar}.AllowAnonymous();");
        }

        if (group.RequireAuthorization) {
            sb.Append($"{groupVar}.RequireAuthorization(");

            if (group.AuthorizationPolicy is not null) {
                sb.Append($"\"{EscapeStringLiteral(group.AuthorizationPolicy)}\"");
            }

            sb.AppendLine(");");
        }

        if (group.RequestTimeoutPolicy is not null) {
            sb.AppendLine($"{groupVar}.WithRequestTimeout(\"{EscapeStringLiteral(group.RequestTimeoutPolicy)}\");");
        }

        if (group.DisableRequestTimeout) {
            sb.AppendLine($"{groupVar}.DisableRequestTimeout();");
        }

        // AllowCookieRedirectAttribute is intentionally propagated: applying it to a
        // RouteGroupBuilder configures challenge-response cookie redirect semantics for
        // the whole group, which is distinct from the no-op documentation-only intent
        // the attribute carries at the individual endpoint level.
        if (group.AllowCookieRedirect) {
            sb.AppendLine($"{groupVar}.AllowCookieRedirect();");
        }

        foreach (var filter in group.FilterTypeNames) {
            sb.AppendLine($"{groupVar}.AddEndpointFilter<{filter}>();");
        }
    }
}
