using System.Text;
using Microsoft.CodeAnalysis;
using Nameless.Web.Http.Endpoints.Generator.Infrastructure;
using Nameless.Web.Http.Endpoints.Generator.Models;

namespace Nameless.Web.Http.Endpoints.Generator.Emitters;

public static class RegistrationEmitter {
    private const string SERVICES_ARG = "services";
    private const string BUILDER_ARG = "builder";
    private const string CONFIG_API_VERSIONING_ARG = "configureApiVersioning";
    private const string CONFIG_API_EXPLORER_ARG = "configureApiExplorer";

    public static void Emit(SourceProductionContext context, DiagnosticAwareResult<GroupingModel[]> input) {
        var (groups, diagnostics) = (input.Model ?? [], input.Diagnostics);

        foreach (var diagnostic in diagnostics) {
            context.ReportDiagnostic(diagnostic.ToDiagnostic());
        }

        if (groups.Length == 0) { return; }

        // Emit per-endpoint partial classes
        foreach (var group in groups) {
            foreach (var endpoint in group.Endpoints) {
                var (epHint, epSource) = EndpointEmitter.Emit(endpoint);
                context.AddSource(epHint, epSource);
            }
            
            // Emit group partial class
            var (groupHint, groupSource) = EndpointGroupEmitter.Emit(group);
            context.AddSource(groupHint, groupSource);
        }

        // Emit the delegating registration extensions file
        var cw = new CodeWriter();

        EmitFileHeader(cw);
        EmitClass(cw, groups);

        var code = cw.ToString();

        context.AddSource(
            hintName: $"{Project.RegistrationClassName}.g.cs",
            source: code
        );
    }

    private static void EmitFileHeader(CodeWriter cw) {
        cw.WriteLine("// <auto-generated/>");
        cw.WriteLine($"// Generated by {Project.Name} — do not edit.");
        cw.WriteLine("#nullable enable");
        cw.WriteLine();
        cw.WriteLine("using global::Asp.Versioning;");
        cw.WriteLine("using global::Asp.Versioning.ApiExplorer;");
        cw.WriteLine("using global::Microsoft.AspNetCore.Builder;");
        cw.WriteLine("using global::Microsoft.AspNetCore.Http;");
        cw.WriteLine("using global::Microsoft.AspNetCore.Routing;");
        cw.WriteLine("using global::Microsoft.Extensions.DependencyInjection;");
        cw.WriteLine("using global::Microsoft.Extensions.DependencyInjection.Extensions;");
        cw.WriteLine();
        cw.WriteLine($"namespace {Project.Namespace};");
        cw.WriteLine();
    }

    private static void EmitClass(CodeWriter cw, GroupingModel[] groups) {
        using (cw.Block($"public static class {Project.RegistrationClassName} {{")) {
            cw.WriteLine();
            EmitRegisterEndpointsMethod(cw, groups);

            cw.WriteLine();
            EmitMapEndpointsMethod(cw, groups);
        }
    }

    private static void EmitRegisterEndpointsMethod(CodeWriter cw, GroupingModel[] groups) {
        var opening = new StringBuilder();

        opening.Append($"public static {FQN.Microsoft.ServiceCollection} {Project.RegisterEndpointsMethodName}(");
        opening.Append($"this {FQN.Microsoft.ServiceCollection} {SERVICES_ARG}, ");
        opening.Append($"{FQN.System.Action}<{FQN.AspVersioning.ApiVersioningOptions}>? {CONFIG_API_VERSIONING_ARG} = null, ");
        opening.Append($"{FQN.System.Action}<{FQN.AspVersioning.ApiExplorerOptions}>? {CONFIG_API_EXPLORER_ARG} = null");
        opening.Append(") {");

        using (cw.Block(opening.ToString())) {
            foreach (var group in groups) {
                foreach (var endpoint in group.Endpoints) {
                    cw.WriteLine($"global::{endpoint.Class.FullName}.Register({SERVICES_ARG});");
                }
            }

            cw.WriteLine();
            EmitApiVersioningConfiguration(cw);

            cw.WriteLine($"return {SERVICES_ARG};");
        }

        cw.WriteLine();
        EmitDefaultApiVersioningConfiguration(cw);

        cw.WriteLine();
        EmitDefaultApiExplorerConfiguration(cw);
    }

    private static void EmitApiVersioningConfiguration(CodeWriter cw) {
        using (cw.Block(SERVICES_ARG, closing: string.Empty)) {
            cw.WriteLine($".AddApiVersioning({CONFIG_API_VERSIONING_ARG} ?? DefaultApiVersioningConfiguration)");
            cw.WriteLine($".AddApiExplorer({CONFIG_API_EXPLORER_ARG} ?? DefaultApiExplorerConfiguration);");
        }
    }

    private static void EmitDefaultApiVersioningConfiguration(CodeWriter cw) {
        using (cw.Block("private static void DefaultApiVersioningConfiguration(ApiVersioningOptions options) {")) {
            cw.WriteLine("options.ReportApiVersions = true;");
            cw.WriteLine("options.AssumeDefaultVersionWhenUnspecified = true;");
            //cw.WriteLine("options.DefaultApiVersion = new ApiVersion(majorVersion: 1);");
            using (cw.Block("options.ApiVersionReader = ApiVersionReader.Combine(", closing: ");")) {
                cw.WriteLine("new UrlSegmentApiVersionReader(), new HeaderApiVersionReader(\"api-version\")");
            }
        }
    }

    private static void EmitDefaultApiExplorerConfiguration(CodeWriter cw) {
        using (cw.Block("private static void DefaultApiExplorerConfiguration(ApiExplorerOptions options) {")) {
            cw.WriteLine("options.GroupNameFormat = \"'v'VVV\";");
            cw.WriteLine("options.SubstituteApiVersionInUrl = false;");
        }
    }

    private static void EmitMapEndpointsMethod(CodeWriter cw, GroupingModel[] groups) {
        using (cw.Block($"public static {FQN.Microsoft.EndpointRouteBuilder} {Project.MapEndpointsMethodName}(this {FQN.Microsoft.EndpointRouteBuilder} {BUILDER_ARG}) {{")) {
            foreach (var group in groups) {
                EmitEndpointGroupMapping(cw, group);
                cw.WriteLine();
            }

            cw.WriteLine($"return {BUILDER_ARG};");
        }
    }

    private static void EmitEndpointGroupMapping(CodeWriter sb, GroupingModel grouping) {
        var groupVar = $"_g_{Sanitize(grouping.Class.FullName)}";
        sb.WriteLine($"var {groupVar} = global::{grouping.Class.FullName}.Create({BUILDER_ARG});");

        foreach (var endpoint in grouping.Endpoints) {
            sb.WriteLine($"global::{endpoint.Class.FullName}.Map({groupVar});");
        }
    }
}
