using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Nameless.Web.Http.Endpoints.Generator.Models;
using Nameless.Web.Http.Endpoints.Generator.Pipeline;

namespace Nameless.Web.Http.Endpoints.Generator.Emitters;

internal static class RegistrationEmitter {
    private const string CONFIG_API_VERSIONING_ARG = "configureApiVersioning";
    private const string CONFIG_API_EXPLORER_ARG = "configureApiExplorer";

    internal static void Emit(SourceProductionContext context, GroupCollectionMetadata input) {
        var (groups, diagnostics) = input;

        foreach (var diagnostic in diagnostics) {
            context.ReportDiagnostic(diagnostic.ToDiagnostic());
        }

        if (groups.IsEmpty) {
            return;
        }

        // Emit per-endpoint partial classes
        foreach (var group in groups) {
            foreach (var endpoint in group.Endpoints) {
                var (epHint, epSource) = EndpointEmitter.Emit(endpoint);
                context.AddSource(epHint, epSource);
            }

            if (!group.IsExplicit) { continue; }

            // Emit group partial class (explicit groups only)
            var groupingMetadata = GroupEmitter.Emit(group);
            context.AddSource(
                groupingMetadata.HintName,
                groupingMetadata.Source
            );
        }

        // Emit the delegating registration extensions file
        var sb = new StringBuilder();

        EmitFileHeader(sb);
        EmitRegisterEndpoints(sb, groups);
        EmitMapEndpoints(sb, groups);
        EmitFileFooter(sb);

        var code = sb.ToString();
        var tree = CSharpSyntaxTree.ParseText(code);
        var root = tree.GetRoot().NormalizeWhitespace();

        context.AddSource(
            hintName: $"{FQN.GENERATED_NAMESPACE}.g.cs",
            source: root.ToFullString()
        );
    }

    private static void EmitFileHeader(StringBuilder sb) {
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine($"// Generated by {PROJECT_NAME} — do not edit.");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using global::Asp.Versioning;");
        sb.AppendLine("using global::Asp.Versioning.ApiExplorer;");
        sb.AppendLine("using global::Microsoft.AspNetCore.Builder;");
        sb.AppendLine("using global::Microsoft.AspNetCore.Http;");
        sb.AppendLine("using global::Microsoft.AspNetCore.Routing;");
        sb.AppendLine("using global::Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using global::Microsoft.Extensions.DependencyInjection.Extensions;");
        sb.AppendLine();
        sb.AppendLine($"namespace {FQN.GENERATED_NAMESPACE};");
        sb.AppendLine();
        sb.AppendLine("internal static class EndpointRegistrationExtensions");
        sb.AppendLine("{");
    }

    private static void EmitRegisterEndpoints(StringBuilder sb, ImmutableArray<GroupModel> groups) {
        sb.Append($"internal static {ClassNames.SERVICE_COLLECTION} {REGISTER_ENDPOINTS_METHOD_NAME}(");
        sb.Append($"this {ClassNames.SERVICE_COLLECTION} {SELF_REF}, ");
        sb.Append($"{ClassNames.ACTION}<{ClassNames.API_VERSIONING_OPTIONS}>? {CONFIG_API_VERSIONING_ARG} = null, ");
        sb.Append($"{ClassNames.ACTION}<{ClassNames.API_EXPLORER_OPTIONS}>? {CONFIG_API_EXPLORER_ARG} = null");
        sb.Append(") {");

        foreach (var group in groups) {
            foreach (var endpoint in group.Endpoints) {
                sb.AppendLine($"global::{endpoint.FullClassName}.Register({SELF_REF});");
            }
        }

        EmitApiVersioningConfiguration(sb);

        sb.AppendLine($"return {SELF_REF};");
        sb.AppendLine("}");

        EmitDefaultApiVersioningConfiguration(sb);
        EmitDefaultApiExplorerConfiguration(sb);

        sb.AppendLine();
    }

    private static void EmitApiVersioningConfiguration(StringBuilder sb) {
        sb.Append($"{SELF_REF}");
        sb.Append($".AddApiVersioning({CONFIG_API_VERSIONING_ARG} ?? DefaultApiVersioningConfiguration)");
        sb.Append($".AddApiExplorer({CONFIG_API_EXPLORER_ARG} ?? DefaultApiExplorerConfiguration)");
        sb.Append(';');
    }

    private static void EmitDefaultApiVersioningConfiguration(StringBuilder sb) {
        sb.AppendLine("private static void DefaultApiVersioningConfiguration(ApiVersioningOptions options) {");
        sb.AppendLine("options.ReportApiVersions = true;");
        sb.AppendLine("options.AssumeDefaultVersionWhenUnspecified = true;");
        sb.AppendLine("options.DefaultApiVersion = new ApiVersion(majorVersion: 1);");
        sb.AppendLine("options.ApiVersionReader = ApiVersionReader.Combine(");
        sb.AppendLine("new UrlSegmentApiVersionReader(), new HeaderApiVersionReader(\"api-version\"));");
        sb.AppendLine("}");
    }

    private static void EmitDefaultApiExplorerConfiguration(StringBuilder sb) {
        sb.AppendLine("private static void DefaultApiExplorerConfiguration(ApiExplorerOptions options) {");
        sb.AppendLine("options.GroupNameFormat = \"'v'VVV\";");
        sb.AppendLine("options.SubstituteApiVersionInUrl = false;");
        sb.AppendLine("}");
    }

    private static void EmitMapEndpoints(StringBuilder sb, ImmutableArray<GroupModel> groups) {
        sb.AppendLine($"internal static {FQN.ENDPOINT_ROUTE_BUILDER} {MAP_ENDPOINTS_METHOD_NAME}(this {FQN.ENDPOINT_ROUTE_BUILDER} {SELF_REF}) {{");

        foreach (var group in groups) {
            if (group.IsExplicit) {
                EmitExplicitGroup(sb, group);
                continue;
            }
            
            if (!string.IsNullOrEmpty(group.Name)) {
                EmitSyntheticVersionedGroup(sb, group);
                continue;
            }

            EmitUngroupedEndpoints(sb, group);
        }

        sb.AppendLine($"return {SELF_REF};");
        sb.AppendLine("}");
        sb.AppendLine();
    }

    private static void EmitExplicitGroup(StringBuilder sb, GroupModel group) {
        var groupVar = $"__group_{Sanitize(group.Name)}";
        sb.AppendLine($"var {groupVar} = global::{group.FullClassName}.Create({SELF_REF});");

        foreach (var endpoint in group.Endpoints) {
            sb.AppendLine($"global::{endpoint.FullClassName}.Map({groupVar});");
        }
    }

    // Synthetic Versioned Groups are endpoints that have distinct versions but do not belong to
    // a particular group. In that case, they need to be "grouped" under a group so they can
    // be correctly versioned.
    private static void EmitSyntheticVersionedGroup(StringBuilder sb, GroupModel group) {
        var versionSetVar = $"_version_set_{Sanitize(group.Name)}";
        var groupVar = $"_group_{Sanitize(group.Name)}";

        sb.AppendLine($"var {versionSetVar} = {SELF_REF}.NewApiVersionSet()");

        foreach (var version in group.Versions) {
            var method = version.Deprecated ? "HasDeprecatedApiVersion" : "HasApiVersion";
            sb.AppendLine($".{method}(new {FQN.API_VERSION}({version.Major}, {version.Minor}))");
        }

        sb.AppendLine(".ReportApiVersions().Build();");
        sb.AppendLine($"var {groupVar} = {SELF_REF}.MapGroup(\"\");");
        sb.AppendLine($"{groupVar}.WithApiVersionSet({versionSetVar});");

        foreach (var endpoint in group.Endpoints) {
            sb.AppendLine($"global::{endpoint.FullClassName}.Map({groupVar});");
        }
    }

    private static void EmitUngroupedEndpoints(StringBuilder sb, GroupModel group) {
        foreach (var endpoint in group.Endpoints) {
            sb.AppendLine($"global::{endpoint.FullClassName}.Map({SELF_REF});");
        }
    }

    private static void EmitFileFooter(StringBuilder sb) {
        sb.AppendLine("}");
    }
}
