using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Nameless.Web.Http.Endpoints.Generator.Models;
using Nameless.Web.Http.Endpoints.Generator.Pipeline;

namespace Nameless.Web.Http.Endpoints.Generator.Emitters;

internal static class RegistrationEmitter {
    private const string CONFIG_API_VERSIONING_ARG = "configureApiVersioning";
    private const string CONFIG_API_EXPLORER_ARG = "configureApiExplorer";

    internal static void Emit(SourceProductionContext context, GroupCollectionMetadata input) {
        var (groups, diagnostics) = input;

        foreach (var diagnostic in diagnostics) {
            context.ReportDiagnostic(diagnostic.ToDiagnostic());
        }

        if (groups.IsEmpty) {
            return;
        }

        var sb = new StringBuilder();

        EmitFileHeader(sb);
        EmitRegisterEndpoints(sb, groups);
        EmitMapEndpoints(sb, groups);
        EmitFileFooter(sb);

        // Organize and indent the code
        var code = sb.ToString();
        var tree = CSharpSyntaxTree.ParseText(code);
        var root = tree.GetRoot().NormalizeWhitespace();
        
        context.AddSource(
            hintName: $"{FQN.GENERATED_NAMESPACE}.g.cs",
            source: root.ToFullString()
        );
    }

    private static void EmitFileHeader(StringBuilder sb) {
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine($"// Generated by {PROJECT_NAME} — do not edit.");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using global::Asp.Versioning;");
        sb.AppendLine("using global::Asp.Versioning.ApiExplorer;");
        sb.AppendLine("using global::Microsoft.AspNetCore.Builder;");
        sb.AppendLine("using global::Microsoft.AspNetCore.Http;");
        sb.AppendLine("using global::Microsoft.AspNetCore.Routing;");
        sb.AppendLine("using global::Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using global::Microsoft.Extensions.DependencyInjection.Extensions;");
        sb.AppendLine();
        sb.AppendLine($"namespace {FQN.GENERATED_NAMESPACE};");
        sb.AppendLine();
        sb.AppendLine("internal static class EndpointRegistrationExtensions");
        sb.AppendLine("{");
    }

    private static void EmitRegisterEndpoints(StringBuilder sb, ImmutableArray<GroupModel> groups) {
        sb.Append($"internal static {ClassNames.SERVICE_COLLECTION} {REGISTER_ENDPOINTS_METHOD_NAME}(");
        sb.Append($"this {ClassNames.SERVICE_COLLECTION} {SELF_REF}, ");
        sb.Append($"{ClassNames.ACTION}<{ClassNames.API_VERSIONING_OPTIONS}>? {CONFIG_API_VERSIONING_ARG} = null, ");
        sb.Append($"{ClassNames.ACTION}<{ClassNames.API_EXPLORER_OPTIONS}>? {CONFIG_API_EXPLORER_ARG} = null");
        sb.Append(") {");

        foreach (var group in groups) {
            foreach (var endpoint in group.Endpoints) {
                sb.AppendLine($"{SELF_REF}.TryAddTransient<global::{endpoint.FullClassName}>();");
            }
        }

        EmitApiVersioningConfiguration(sb);

        sb.AppendLine($"return {SELF_REF};");
        sb.AppendLine("}");

        EmitDefaultApiVersioningConfiguration(sb);
        EmitDefaultApiExplorerConfiguration(sb);

        sb.AppendLine();
    }

    private static void EmitApiVersioningConfiguration(StringBuilder sb) {
        sb.Append($"{SELF_REF}");

        sb.Append($".AddApiVersioning({CONFIG_API_VERSIONING_ARG} ?? DefaultApiVersioningConfiguration)");
        sb.Append($".AddApiExplorer({CONFIG_API_EXPLORER_ARG} ?? DefaultApiExplorerConfiguration)");

        sb.Append(';');
    }

    private static void EmitDefaultApiVersioningConfiguration(StringBuilder sb) {
        sb.AppendLine("private static void DefaultApiVersioningConfiguration(ApiVersioningOptions options) {");
        sb.AppendLine("// Add the headers \"api-supported-versions\" and \"api-deprecated-versions\"");
        sb.AppendLine("// This is better for discoverability");
        sb.AppendLine("options.ReportApiVersions = true;");

        sb.AppendLine("// AssumeDefaultVersionWhenUnspecified should only be enabled when");
        sb.AppendLine("// supporting legacy services that did not previously support API");
        sb.AppendLine("// versioning. Forcing existing clients to specify an explicit API");
        sb.AppendLine("// version for an existing service introduces a breaking change.");
        sb.AppendLine("// Conceptually, clients in this situation are bound to some API");
        sb.AppendLine("// version of a service, but they don't know what it is and never");
        sb.AppendLine("// explicit request it.");
        sb.AppendLine("options.AssumeDefaultVersionWhenUnspecified = true;");
        sb.AppendLine("options.DefaultApiVersion = new ApiVersion(majorVersion: 1);");
        
        sb.AppendLine("// Defines how an API version is read from the current HTTP request");
        sb.AppendLine("options.ApiVersionReader = ApiVersionReader.Combine(");
        sb.AppendLine("new UrlSegmentApiVersionReader(), new HeaderApiVersionReader(\"api-version\"));");
        sb.AppendLine("}");
    }

    private static void EmitDefaultApiExplorerConfiguration(StringBuilder sb) {
        sb.AppendLine("private static void DefaultApiExplorerConfiguration(ApiExplorerOptions options) {");
        sb.AppendLine("// add the versioned api explorer, which also adds");
        sb.AppendLine("// IApiVersionDescriptionProvider service");
        sb.AppendLine("// note: the specified format code will format the version");
        sb.AppendLine("// as \"'v'major[.minor][-status]\"");
        sb.AppendLine("options.GroupNameFormat = \"'v'VVV\";");
        
        sb.AppendLine("// note: this option is only necessary when versioning by url segment.");
        sb.AppendLine("// The SubstitutionFormat can also be used to control the format of");
        sb.AppendLine("// the API version in route templates.");
        sb.AppendLine("options.SubstituteApiVersionInUrl = false;");
        sb.AppendLine("}");
    }

    private static void EmitMapEndpoints(StringBuilder sb, ImmutableArray<GroupModel> groups) {
        sb.AppendLine($"internal static {FQN.ENDPOINT_ROUTE_BUILDER} {MAP_ENDPOINTS_METHOD_NAME}(this {FQN.ENDPOINT_ROUTE_BUILDER} {SELF_REF}) {{");

        foreach (var group in groups) {
            GroupEmitter.Emit(sb, group);
        }

        sb.AppendLine($"return {SELF_REF};");
        sb.AppendLine("}");
        sb.AppendLine();
    }

    private static void EmitFileFooter(StringBuilder sb) {
        sb.AppendLine("}");
    }
}
