using System.Diagnostics.CodeAnalysis;
using Microsoft.Extensions.Logging;
using Nameless.Workers;

namespace Nameless;

[ExcludeFromCodeCoverage(Justification = CodeCoverage.Justifications.AutoGeneratedCode)]
internal static partial class Log {
    #region Common

    [LoggerMessage(level: LogLevel.Error, message: "[{Tag}] An error has occurred while executing action '{ActionName}'.")]
    internal static partial void Failure(ILogger logger, string tag, string actionName, Exception exception);

    #endregion

    #region Workers

    [LoggerMessage(level: LogLevel.Information, message: "[{Tag}] Worker '{WorkerName}' status changed to '{Status}'.")]
    internal static partial void WorkerStatusChanged(ILogger logger, string tag, string workerName, WorkerStatus status);

    #endregion
}
