//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nameless.WinApp.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Translation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nameless.WinApp.Resources.Localization.Translation", typeof(Translation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abrir Diretório da Aplicação.
        /// </summary>
        internal static string AppConfigurationPage_AppDirectoryPathCard_Button_Caption {
            get {
                return ResourceManager.GetString("AppConfigurationPage_AppDirectoryPathCard_Button_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O diretório que contêm todos os dados da aplicação, bem como arquivos de configuração, suporte e logs..
        /// </summary>
        internal static string AppConfigurationPage_AppDirectoryPathCard_Message {
            get {
                return ResourceManager.GetString("AppConfigurationPage_AppDirectoryPathCard_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diretório de Dados da Aplicação.
        /// </summary>
        internal static string AppConfigurationPage_AppDirectoryPathCard_Title {
            get {
                return ResourceManager.GetString("AppConfigurationPage_AppDirectoryPathCard_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criar Backup da Aplicação.
        /// </summary>
        internal static string AppConfigurationPage_ApplicationBackupCard_Button_Caption {
            get {
                return ResourceManager.GetString("AppConfigurationPage_ApplicationBackupCard_Button_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crie uma cópia das bases de dados da aplicação em caso de desastre..
        /// </summary>
        internal static string AppConfigurationPage_ApplicationBackupCard_Message {
            get {
                return ResourceManager.GetString("AppConfigurationPage_ApplicationBackupCard_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup da Aplicação.
        /// </summary>
        internal static string AppConfigurationPage_ApplicationBackupCard_Title {
            get {
                return ResourceManager.GetString("AppConfigurationPage_ApplicationBackupCard_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abrir Log da Aplicação.
        /// </summary>
        internal static string AppConfigurationPage_ApplicationLogCard_Button_Caption {
            get {
                return ResourceManager.GetString("AppConfigurationPage_ApplicationLogCard_Button_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abrir o arquivo de log no editor padrão..
        /// </summary>
        internal static string AppConfigurationPage_ApplicationLogCard_Message {
            get {
                return ResourceManager.GetString("AppConfigurationPage_ApplicationLogCard_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log da Aplicação.
        /// </summary>
        internal static string AppConfigurationPage_ApplicationLogCard_Title {
            get {
                return ResourceManager.GetString("AppConfigurationPage_ApplicationLogCard_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurar Dados da Aplicação.
        /// </summary>
        internal static string AppConfigurationPage_ApplicationRestoreCard_Button_Caption {
            get {
                return ResourceManager.GetString("AppConfigurationPage_ApplicationRestoreCard_Button_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaura os dados da aplicação a partir de um arquivo de backup..
        /// </summary>
        internal static string AppConfigurationPage_ApplicationRestoreCard_Message {
            get {
                return ResourceManager.GetString("AppConfigurationPage_ApplicationRestoreCard_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurar Aplicação.
        /// </summary>
        internal static string AppConfigurationPage_ApplicationRestoreCard_Title {
            get {
                return ResourceManager.GetString("AppConfigurationPage_ApplicationRestoreCard_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja que a aplicação sempre pergunte antes de sair?.
        /// </summary>
        internal static string AppConfigurationPage_ExitBehaviorCard_Message {
            get {
                return ResourceManager.GetString("AppConfigurationPage_ExitBehaviorCard_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmação ao Sair.
        /// </summary>
        internal static string AppConfigurationPage_ExitBehaviorCard_Title {
            get {
                return ResourceManager.GetString("AppConfigurationPage_ExitBehaviorCard_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione a aparência da aplicação.
        /// </summary>
        internal static string AppConfigurationPage_ThemeCard_Message {
            get {
                return ResourceManager.GetString("AppConfigurationPage_ThemeCard_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tema da Aplicação.
        /// </summary>
        internal static string AppConfigurationPage_ThemeCard_Title {
            get {
                return ResourceManager.GetString("AppConfigurationPage_ThemeCard_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aparência &amp; Comportamento.
        /// </summary>
        internal static string AppConfigurationPage_Title {
            get {
                return ResourceManager.GetString("AppConfigurationPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verificar Atualização do Sistema.
        /// </summary>
        internal static string AppConfigurationPage_VersionCard_Button_Caption {
            get {
                return ResourceManager.GetString("AppConfigurationPage_VersionCard_Button_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versão Atual.
        /// </summary>
        internal static string AppConfigurationPage_VersionCard_Title {
            get {
                return ResourceManager.GetString("AppConfigurationPage_VersionCard_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criar Diretórios Aplicação.
        /// </summary>
        internal static string EnsureApplicationDirectoriesExistenceStep_DisplayName {
            get {
                return ResourceManager.GetString("EnsureApplicationDirectoriesExistenceStep_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criando diretório de arquivos de backup....
        /// </summary>
        internal static string EnsureApplicationDirectoriesExistenceStep_ExecuteAsync_CreateBackupDirectory {
            get {
                return ResourceManager.GetString("EnsureApplicationDirectoriesExistenceStep_ExecuteAsync_CreateBackupDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criando diretório de arquivos de banco de dados....
        /// </summary>
        internal static string EnsureApplicationDirectoriesExistenceStep_ExecuteAsync_CreateDatabaseDirectory {
            get {
                return ResourceManager.GetString("EnsureApplicationDirectoriesExistenceStep_ExecuteAsync_CreateDatabaseDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criando diretório de arquivos temporários....
        /// </summary>
        internal static string EnsureApplicationDirectoriesExistenceStep_ExecuteAsync_CreateTemporaryDirectory {
            get {
                return ResourceManager.GetString("EnsureApplicationDirectoriesExistenceStep_ExecuteAsync_CreateTemporaryDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criando diretório de arquivos de atualização....
        /// </summary>
        internal static string EnsureApplicationDirectoriesExistenceStep_ExecuteAsync_CreateUpdateDirectory {
            get {
                return ResourceManager.GetString("EnsureApplicationDirectoriesExistenceStep_ExecuteAsync_CreateUpdateDirectory", resourceCulture);
            }
        }
    }
}
