using Microsoft.CodeAnalysis;
using Nameless.Generators.Infrastructure;

namespace Nameless.Generators.Emitters;

public abstract class EmitterBase<TModel> where TModel : IEmitModel {
    public void Emit(SourceProductionContext context, TModel model, bool prettify = false) {
        Emit(context, new DiagnosticAwareResult<TModel>(model, diagnostics: []), prettify);
    }

    public void Emit(SourceProductionContext context, DiagnosticAwareResult<TModel> result) {
        Emit(context, result, prettify: false);
    }

    public virtual void Emit(SourceProductionContext context, DiagnosticAwareResult<TModel> result, bool prettify) {
        foreach (var diagnostic in result.Diagnostics) {
            context.ReportDiagnostic(diagnostic.ToDiagnostic());
        }

        if (!result.Successful) { return;}

        var model = result.Model ?? throw new InvalidOperationException($"Property '{nameof(DiagnosticAwareResult<>.Model)}' is null.");
        var cw = new CodeWriter();

        EmitFileHeader(cw, model);
        EmitUsingBlock(cw, model);
        EmitFileContent(cw, model);
        EmitFileFooter(cw, model);

        context.AddSource(
            hintName: $"{Sanitize(model.Class.FullName)}.g.cs",
            source: cw.GetCode(prettify)
        );
    }

    protected virtual void EmitFileHeader(CodeWriter cw, TModel model) {
        cw.WriteLine("// <auto-generated/>");
        cw.WriteLine("// ********************************************************************************");
        cw.WriteLine("// Generated by Nameless Generators — do not edit.");
        cw.WriteLine("// ********************************************************************************");
        cw.WriteLine("#nullable enable");
        cw.WriteLine("#pragma warning disable CS1591");
        cw.WriteLine();
    }

    protected virtual void EmitUsingBlock(CodeWriter cw, TModel model) {
        cw.WriteLine("using global::System;");
        cw.WriteLine("using global::System.Collections.Generic;");
        cw.WriteLine("using global::System.Globalization;");
        cw.WriteLine("using global::System.Threading;");
        cw.WriteLine("using global::System.Threading.Tasks;");

        cw.WriteLine("using global::Microsoft.Extensions.DependencyInjection;");
        cw.WriteLine("using global::Microsoft.Extensions.DependencyInjection.Extensions;");

        cw.WriteLine();
    }

    protected abstract void EmitFileContent(CodeWriter cw, TModel model);

    protected virtual void EmitFileFooter(CodeWriter cw, TModel model) {
        cw.WriteLine();
        cw.WriteLine($"// EOF: {Sanitize(model.Class.FullName)}.g.cs");
    }
}