using Nameless.Web.Generators.Infrastructure;
using Nameless.Web.Generators.Models;

namespace Nameless.Web.Generators.Emitters;

public readonly record struct Class {
    public string HintName { get; }
    public string SourceCode { get; }

    public Class(string hintName, string sourceCode) {
        HintName = hintName;
        SourceCode = sourceCode;
    }
}

public abstract class Emitter<TModel> where TModel : IEmitModel {
    public virtual Class Emit(TModel model, bool prettify = false) {
        var cw = new CodeWriter();

        EmitFileHeader(cw, model);
        EmitUsingBlock(cw, model);
        EmitFileContent(cw, model);
        EmitFileFooter(cw, model);

        return new Class(
            hintName: $"{Sanitize(model.Class.FullName)}.g.cs",
            sourceCode: cw.GetCode(prettify)
        );
    }

    protected virtual void EmitFileHeader(CodeWriter cw, TModel model) {
        cw.WriteLine("// <auto-generated/>");
        cw.WriteLine("// ********************************************************************************");
        cw.WriteLine($"// Generated by {Project.Name} — do not edit.");
        cw.WriteLine("// ********************************************************************************");
        cw.WriteLine("#nullable enable");
        cw.WriteLine("#pragma warning disable CS1591");
        cw.WriteLine();
    }

    protected virtual void EmitUsingBlock(CodeWriter cw, TModel model) {
        cw.WriteLine("using global::System;");
        cw.WriteLine("using global::System.Collections.Generic;");
        cw.WriteLine("using global::System.Globalization;");
        cw.WriteLine("using global::System.Threading.Tasks;");

        cw.WriteLine("using global::Asp.Versioning;");
        cw.WriteLine("using global::Asp.Versioning.ApiExplorer;");

        cw.WriteLine("using global::Microsoft.AspNetCore.Authorization;");
        cw.WriteLine("using global::Microsoft.AspNetCore.Builder;");
        cw.WriteLine("using global::Microsoft.AspNetCore.Cors;");
        cw.WriteLine("using global::Microsoft.AspNetCore.Http;");
        cw.WriteLine("using global::Microsoft.AspNetCore.Http.Timeouts;");
        cw.WriteLine("using global::Microsoft.AspNetCore.Mvc;");
        cw.WriteLine("using global::Microsoft.AspNetCore.OutputCaching;");
        cw.WriteLine("using global::Microsoft.AspNetCore.RateLimiting;");
        cw.WriteLine("using global::Microsoft.AspNetCore.Routing;");
        cw.WriteLine("using global::Microsoft.OpenApi;");

        cw.WriteLine("using global::Microsoft.Extensions.DependencyInjection;");
        cw.WriteLine("using global::Microsoft.Extensions.DependencyInjection.Extensions;");

        cw.WriteLine("using Nameless.Web.Filters.Validation;");
        cw.WriteLine($"using global::{Project.Namespaces.Attributes.Versioning};");
        cw.WriteLine();
    }

    protected abstract void EmitFileContent(CodeWriter cw, TModel model);

    protected virtual void EmitFileFooter(CodeWriter cw, TModel model) {
        cw.WriteLine();
        cw.WriteLine($"// EOF: {Sanitize(model.Class.FullName)}.g.cs");
    }
}

public interface IEmitModel {
    ClassModel Class { get; }
}