<Project Sdk="Aspire.AppHost.Sdk/13.4.2">

	<PropertyGroup>
		<RootNamespace>Nameless.Microservices.AppHost</RootNamespace>
		<OutputType>Exe</OutputType>
		<IsAspireHost>True</IsAspireHost>
		<UserSecretsId>c106ace1-b41b-44b5-86e2-61a4604de345</UserSecretsId>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Aspire.Hosting.AppHost" />
		<PackageReference Include="Aspire.Hosting.JavaScript" />
		<PackageReference Include="Aspire.Hosting.PostgreSQL" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Nameless.Microservices.Api\Nameless.Microservices.Api.csproj" />
	</ItemGroup>

</Project>
