using System.Diagnostics.CodeAnalysis;
using Microsoft.Extensions.Logging;
using Nameless.Diagnostics.CodeAnalysis;

namespace Nameless.Application;

[ExcludeFromCodeCoverage(Justification = CodeCoverage.Justifications.AutoGeneratedCode)]
internal static partial class Log {
    private const string TAG = "APPLICATION_CONTEXT";

    [LoggerMessage(LogLevel.Error, message: "[{Tag}] An error has occurred while creating the File System Provider.")]
    internal static partial void CreateFileSystemProviderFailure(ILogger<ApplicationContext> logger, Exception exception, string tag = TAG);
}