//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nameless.WPF.Client.Lucene.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nameless.WPF.Client.Lucene.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicializar Base de Dados Lucene.
        /// </summary>
        internal static string InitializeLuceneStep_Name {
            get {
                return ResourceManager.GetString("InitializeLuceneStep_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total de documentos na base de dados {0}.
        /// </summary>
        internal static string InitializeLuceneStep_Progress_DocumentCount {
            get {
                return ResourceManager.GetString("InitializeLuceneStep_Progress_DocumentCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicializando indíce único....
        /// </summary>
        internal static string InitializeLuceneStep_Progress_Starting {
            get {
                return ResourceManager.GetString("InitializeLuceneStep_Progress_Starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicialização concluída com sucesso..
        /// </summary>
        internal static string InitializeLuceneStep_Progress_Success {
            get {
                return ResourceManager.GetString("InitializeLuceneStep_Progress_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotina de Backup da Base de Dados Lucene.
        /// </summary>
        internal static string LuceneDisasterRecoveryRoutine_Name {
            get {
                return ResourceManager.GetString("LuceneDisasterRecoveryRoutine_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro durante a execução do backup da base de dados Lucene. Erro: {0}.
        /// </summary>
        internal static string LuceneDisasterRecoveryRoutine_Report_Backup_Failure {
            get {
                return ResourceManager.GetString("LuceneDisasterRecoveryRoutine_Report_Backup_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup da base de dados Lucene será ignorado devido a não existência de dados. .
        /// </summary>
        internal static string LuceneDisasterRecoveryRoutine_Report_Backup_Ignore {
            get {
                return ResourceManager.GetString("LuceneDisasterRecoveryRoutine_Report_Backup_Ignore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciando o backup da base de dados Lucene....
        /// </summary>
        internal static string LuceneDisasterRecoveryRoutine_Report_Backup_Starting {
            get {
                return ResourceManager.GetString("LuceneDisasterRecoveryRoutine_Report_Backup_Starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup da base de dados Lucene foi concluído com sucesso..
        /// </summary>
        internal static string LuceneDisasterRecoveryRoutine_Report_Backup_Success {
            get {
                return ResourceManager.GetString("LuceneDisasterRecoveryRoutine_Report_Backup_Success", resourceCulture);
            }
        }
    }
}
