dotnet sln add .\src\Nameless.Skeleton.Web.csproj
dotnet sln add ..\..\src\AspNetCore\Common\src\Nameless.AspNetCore.csproj
dotnet sln add ..\..\src\AspNetCore\Identity\src\Nameless.AspNetCore.Identity.csproj
dotnet sln add ..\..\src\AspNetCore\Identity.NHibernate\src\Nameless.AspNetCore.Identity.NHibernate.csproj
dotnet sln add ..\..\src\AspNetCore\Localization\src\Nameless.AspNetCore.Localization.csproj
dotnet sln add ..\..\src\Core\src\Nameless.Core.csproj
dotnet sln add ..\..\src\DependencyInjection\Abstractions\src\Nameless.DependencyInjection.csproj
dotnet sln add ..\..\src\DependencyInjection\Autofac\extra\Nameless.DependencyInjection.Autofac.Extra.csproj
dotnet sln add ..\..\src\DependencyInjection\Autofac\src\Nameless.DependencyInjection.Autofac.csproj
dotnet sln add ..\..\src\FileStorage\Abstractions\src\Nameless.FileStorage.csproj
dotnet sln add ..\..\src\FileStorage\FileSystem\src\Nameless.FileStorage.FileSystem.csproj
dotnet sln add ..\..\src\FileStorage\FileSystem\extra\Nameless.FileStorage.FileSystem.Extra.csproj
dotnet sln add ..\..\src\Localization\Abstractions\src\Nameless.Localization.csproj
dotnet sln add ..\..\src\Localization\Json\src\Nameless.Localization.Json.csproj
dotnet sln add ..\..\src\Localization\Json\extra\Nameless.Localization.Json.Extra.csproj
dotnet sln add ..\..\src\Logging\Abstractions\src\Nameless.Logging.csproj
dotnet sln add ..\..\src\Logging\Log4net\src\Nameless.Logging.Log4net.csproj
dotnet sln add ..\..\src\Logging\Log4net\extra\Nameless.Logging.Log4net.Extra.csproj
dotnet sln add ..\..\src\Persistence\Abstractions\src\Nameless.Persistence.csproj
dotnet sln add ..\..\src\Persistence\NHibernate\src\Nameless.Persistence.NHibernate.csproj
dotnet sln add ..\..\src\Persistence\NHibernate\extra\Nameless.Persistence.NHibernate.Extra.csproj
dotnet sln add ..\..\src\Serialization\Abstractions\src\Nameless.Serialization.csproj
dotnet sln add ..\..\src\Serialization\Json\src\Nameless.Serialization.Json.csproj
dotnet sln add ..\..\src\Serialization\Json\extra\Nameless.Serialization.Json.Extra.csproj
dotnet sln add ..\..\src\CQRS\Abstractions\src\Nameless.CQRS.csproj
dotnet sln add ..\..\src\CQRS\Common\extra\Nameless.CQRS.Common.Extra.csproj
dotnet sln add ..\..\src\CQRS\Common\src\Nameless.CQRS.Common.csproj
dotnet sln add ..\..\src\Mailing\Abstractions\src\Nameless.Mailing.csproj
dotnet sln add ..\..\src\Mailing\MailKit\src\Nameless.Mailing.MailKit.csproj
dotnet sln add ..\..\src\Mailing\MailKit\extra\Nameless.Mailing.MailKit.Extra.csproj