using System.Data;
using System.Diagnostics.CodeAnalysis;
using Microsoft.Extensions.Logging;
using Nameless.Diagnostics.CodeAnalysis;

namespace Nameless.Data;

[ExcludeFromCodeCoverage(Justification = CodeCoverage.Justifications.AutoGeneratedCode)]
internal static partial class Log {
    private const string TAG = "DATABASE";

    private const string DB_COMMAND_DEBUG_MSG = """
                                                [{Tag}] Executing:
                                                    Command: '{CommandText}'
                                                    Parameters: {@Parameters}
                                                """;

    [LoggerMessage(LogLevel.Error, message: "[{Tag}] An error has occurred while executing non-query statement.")]
    internal static partial void ExecuteNonQueryFailure(ILogger<Database> logger, Exception exception, string tag = TAG);

    [LoggerMessage(LogLevel.Error, message: "[{Tag}] An error has occurred while executing reader statement.")]
    internal static partial void ExecuteReaderFailure(ILogger<Database> logger, Exception exception, string tag = TAG);
    
    [LoggerMessage(LogLevel.Error, message: "[{Tag}] An error has occurred while executing scalar statement.")]
    internal static partial void ExecuteScalarFailure(ILogger<Database> logger, Exception exception, string tag = TAG);
    
    [LoggerMessage(LogLevel.Debug, message: DB_COMMAND_DEBUG_MSG)]
    internal static partial void OutputDbCommandForDebug(ILogger<Database> logger, string commandText, IDataParameterCollection parameters, string tag = TAG);
}