name: Development Cycle

on:

  push:
    branches:
      - 'feature/**'

env:
  CODE_COVERAGE_FOLDER_PATH: './code_coverage'
  CODE_COVERAGE_COBERTURA_FILE_PATH: './code_coverage/**/coverage.cobertura.xml'
  CODE_COVERAGE_REPORT_FOLDER_PATH: './code_coverage/coverage_report'

jobs:

  build_and_test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        dotnet-version: ['8.0.x']

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4.1.1

      - name: Setup .NET
        uses: actions/setup-dotnet@v4.0.0
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Setup GitHub package registry for NuGet
        run: |
          dotnet nuget add source \
          --username ${{ github.repository_owner }} \
          --password ${{ secrets.GITHUB_TOKEN }} \
          --store-password-in-clear-text \
          --name github ${{ vars.NUGET_SOURCE_URL }}

      - name: Restore solution
        run: dotnet restore

      - name: Build solution
        if: success()
        run: |
          dotnet build \
          --configuration Debug \
          --no-restore \
          --verbosity normal

      - name: Run tests
        if: success()
        run: |
          dotnet test \
          --no-restore \
          --no-build \
          --logger:"Html;LogFileName=code-coverage-log.html" \
          --collect:"XPlat Code Coverage" \
          --results-directory ./code-coverage/ \
          --verbosity normal

      - name: Prepare for coverage report
        if: success()
        run: |
          dotnet tool install \
          dotnet-reportgenerator-globaltool \
          --version 5.2.0 \
          --global

      - name: Write coverage report
        if: success()
        run: |
          reportgenerator \
          "-reports:./code-coverage/**/coverage.cobertura.xml" \
          "-targetdir:./code-coverage/report" \
          -reporttypes:Html

      - name: Upload coverage report
        uses: actions/upload-artifact@v3.1.3
        if: success()
        with:
          name: test-coverage-report
          path: ${{ env.CODE_COVERAGE_REPORT_FOLDER_PATH }}
          retention-days: 7