name: Release Cycle

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

env:
  SOLUTION: "./Nameless.sln"
  NUPKG_OUTPUT_PATH: './nupkgs'

jobs:
  release:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dotnet-version: ['9.0.x']

    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v4.2.0
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Get Version Number From Tag
        run: |
          if [[ ${GITHUB_REF} =~ \/v(.*)$ ]]
          then
            echo VERSION=${BASH_REMATCH[1]} >> $GITHUB_ENV
            echo Version ${BASH_REMATCH[1]}
          else
            echo VERSION='1.0.0' >> $GITHUB_ENV
            echo Version 1.0.0
          fi      

      - name: Checkout Source Code
        uses: actions/checkout@v4.2.2

      - name: Register GitHub Package Registry As NuGet Source
        run: >-
          dotnet nuget add source
          --username ${{ github.repository_owner }}
          --password ${{ secrets.GITHUB_TOKEN }}
          --store-password-in-clear-text
          --name github ${{ vars.PACKAGE_SOURCE_URL_GITHUB }}

      - name: Build Solution
        run: >-
          dotnet build ${{ env.SOLUTION }}
          --configuration Release
          --nologo
          --verbosity detailed

      - name: Create NuGet Packages
        run: >-
          dotnet pack
          --configuration Release
          --include-symbols
          --nologo
          --output ${{ env.NUPKG_OUTPUT_PATH }}
          --verbosity normal
          -p:AssemblyVersion=${{ env.VERSION }}
          -p:FileVersion=${{ env.VERSION }}
          -p:PackageVersion=${{ env.VERSION }}
          -p:Version=${{ env.VERSION }}

      - name: Print NuGet Package Directory
        uses: jaywcjlove/github-action-folder-tree@main
        with:
          path: ${{ env.NUPKG_OUTPUT_PATH }}
          depth: 2 

      - name: Publish NuGet Packages
        run: >-
          dotnet nuget push ${{ env.NUPKG_OUTPUT_PATH }}/*.nupkg
          --source ${{ vars.PACKAGE_SOURCE_URL_NUGET_ORG }}
          --api-key ${{ secrets.PACKAGE_SOURCE_API_KEY_NUGET_ORG }}
          --skip-duplicate